<?php

namespace Database\Seeders;

use App\Enums\AccessibilityAccounting;
use App\Enums\AccessibilityHrms;
use App\Enums\AccessibilityInventory;
use App\Enums\AccessibilityProjects;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AccessibilitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // HRMS
        DB::table('accessibilities')->upsert(
            [
                [
                    'id' => 1,
                    'accessibilities_name' => AccessibilityHrms::HRMS_DASHBOARD->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ANNOUNCEMENT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCEPORTAL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_DTR->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_FAILURETOLOG->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 6,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_FACERECOGNITION->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 7,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCELOGIN->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 8,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_QR->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 9,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EVENTCALENDAR->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 10,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 11,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 12,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 13,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 14,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_USERACCOUNT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 15,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_DEPARTMENT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 17,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_APPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 18,
                    'accessibilities_name' => AccessibilityHrms::HRMS_HMO->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 19,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_PAGIBIG->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 20,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_PHILHEALTH->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 21,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_SSS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 22,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_WITHHOLDINGTAX->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 23,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_LEAVES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 24,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 25,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 26,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_LOANS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 27,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_OTHERDEDUCTIONS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 28,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 29,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 30,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_13THMONTH->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 31,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_ALLOWANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 32,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_PAYROLLRECORD->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 33,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 34,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SCHEDULE_DEPARTMENT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 35,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SCHEDULE_EMPLOYEE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 36,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SCHEDULE_PROJECT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 37,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PROJECTMEMBER->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 38,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 39,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 40,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_POSITION->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 41,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_ALLOWANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 42,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_SETTINGS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 43,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_SALARY_GRADE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 44,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_GENERATEPAYROLL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 45,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_GENERATEPAYROLL_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 46,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_GENERATEPAYROLL_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 47,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARYDISBURSEMENT_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 48,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARYDISBURSEMENT_AllREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 49,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARYDISBURSEMENT_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 50,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARYDISBURSEMENT_VIEWPAYSLIPS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 51,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 52,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 53,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 54,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 55,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 56,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 57,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 58,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 59,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 60,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 61,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 62,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 63,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 64,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 65,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 66,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 67,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_EDIT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 68,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_JOBAPPLICANT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 69,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_PIS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 70,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_STAFFINFOSHEET->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 71,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_DOCUMENTSMEMO->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 72,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_ID->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 73,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 74,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 75,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 76,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_MYREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 77,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 78,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 79,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 80,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_MYREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 81,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_CASHADVANCE_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 82,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_CASHADVANCE_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 83,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_CASHADVANCE_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 84,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_LOANS_FORMS->value,
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 85,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_LOANS_ALLREQUESTS->value,
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 86,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_LOANS_PAYMENTS->value,
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 87,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_OTHERDEDUCTIONS_FORMS->value,
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 88,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_OTHERDEDUCTIONS_ALLREQUESTS->value,
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 89,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_LEAVE_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 90,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_LEAVE_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 91,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_LEAVE_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 92,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_OVERTIME_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 93,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_OVERTIME_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 94,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_OVERTIME_MYREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 95,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_OVERTIME_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 96,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_TRAVELORDER_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 97,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_TRAVELORDER_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 98,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_TRAVELORDER_MYREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 99,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_TRAVELORDER_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 100,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCELOGS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 101,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCE_QR->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 102,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 110,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_SSSEMPLOYEEREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 120,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PAGIBIGEMPLOYEEREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 130,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PHILHEALTHEMPLOYEEREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 140,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_SSSGROUPREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 150,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PAGIBIGGROUPREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 160,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PHILHEALTHGROUPREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 170,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_SSSREMITTANCESUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 180,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PAGIBIGREMITTANCESUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 190,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PHILHEALTHREMITTANCESUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ],
            [ "id" ],
            [ "accessibilities_name", "deleted_at"]
        );
        // ACCOUNTING
        DB::table('accessibilities')->upsert(
            [
                [
                    'id' => 1001,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_DASHBOARD,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1002,
                    'accessibilities_name' => "accounting:chart of accounts",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1003,
                    'accessibilities_name' => "accounting:books",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1004,
                    'accessibilities_name' => "accounting:transaction type",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1005,
                    'accessibilities_name' => "accounting:document Series",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1006,
                    'accessibilities_name' => "accounting:posting period",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1007,
                    'accessibilities_name' => "accounting:account groups",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1008,
                    'accessibilities_name' => "accounting:stake holder",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1020,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_JOURNALENTRY_VIEWALL,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1030,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_JOURNALENTRY_CREATE,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1040,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_JOURNALENTRY_MODIFY,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ],
            [ "id" ],
            [ "accessibilities_name", "deleted_at"]
        );
        // INVENTORY
        DB::table('accessibilities')->upsert(
            [
                [
                    'id' => 2006,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2010,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_DASHBOARD->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2020,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_SETUP_APPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2030,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_SETUP_ITEMGROUP->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2040,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_SETUP_UNITOFMEASUREMENT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2050,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_ITEMPROFILE_NEW_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2060,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_ITEMPROFILE_NEW_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2070,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_ITEMPROFILE_NEW_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2080,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_ITEMPROFILE_ITEMLIST->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2090,
                    'accessibilities_name' => AccessibilityInventory::INVENTORY_ITEMPROFILE_NEW_PROFILE->value,
                    'deleted_at' => CArbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ],
            [ "id" ],
            [ "accessibilities_name", "deleted_at"]
        );
        // PROJECT MONITORING
        DB::table('accessibilities')->upsert(
            [
                [
                    'id' => 3001,
                    'accessibilities_name' => AccessibilityProjects::PROJECTMONITORING_DASHBOARD->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3002,
                    'accessibilities_name' => "project_monitoring:projects",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ],
            [ "id" ],
            [ "accessibilities_name", "deleted_at"]
        );
    }
}
