<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AccessibilitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('accessibilities')->upsert(
            [
                [
                    'id' => 1,
                    'accessibilities_name' => "hrms:dashboard",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'accessibilities_name' => "hrms:announcement",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'accessibilities_name' => "hrms:attendance_attendance_portal",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'accessibilities_name' => "hrms:attendance_daily_logs_record",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'accessibilities_name' => "hrms:attendance_failure_to_log",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 6,
                    'accessibilities_name' => "hrms:attendance_face_recognition",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 7,
                    'accessibilities_name' => "hrms:attendance_attendance_login",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 8,
                    'accessibilities_name' => "hrms:attendance_qr_code",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 9,
                    'accessibilities_name' => "hrms:event_calendar",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 10,
                    'accessibilities_name' => "hrms:employee_201",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 11,
                    'accessibilities_name' => "hrms:employee_personnel_action_notice",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 12,
                    'accessibilities_name' => "hrms:employee_onboarding",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 13,
                    'accessibilities_name' => "hrms:employee_manpower_request",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 14,
                    'accessibilities_name' => "hrms:setup_user_account",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 15,
                    'accessibilities_name' => "hrms:setup_department",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 17,
                    'accessibilities_name' => "hrms:setup_approvals",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 18,
                    'accessibilities_name' => "hrms:setup_hmo",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 19,
                    'accessibilities_name' => "hrms:setup_pag_ibig",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 20,
                    'accessibilities_name' => "hrms:setup_phil_health",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 21,
                    'accessibilities_name' => "hrms:setup_sss",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 22,
                    'accessibilities_name' => "hrms:setup_with_holding_tax",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 23,
                    'accessibilities_name' => "hrms:setup_leaves",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 24,
                    'accessibilities_name' => "hrms:leave",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 25,
                    'accessibilities_name' => "hrms:loans_and_advances_cash_advance",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 26,
                    'accessibilities_name' => "hrms:loans_and_advances_loans",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 27,
                    'accessibilities_name' => "hrms:loans_and_advances_other_deductions",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 28,
                    'accessibilities_name' => "hrms:overtime",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 29,
                    'accessibilities_name' => "hrms:payroll_generate_payroll",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 30,
                    'accessibilities_name' => "hrms:payroll_13th_month",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 31,
                    'accessibilities_name' => "hrms:payroll_allowance",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 32,
                    'accessibilities_name' => "hrms:payroll_payroll_report",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 33,
                    'accessibilities_name' => "hrms:reports",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 34,
                    'accessibilities_name' => "hrms:schedule_department_schedule",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 35,
                    'accessibilities_name' => "hrms:schedule_employee_schedule",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 36,
                    'accessibilities_name' => "hrms:schedule_project_schedule",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 37,
                    'accessibilities_name' => "hrms:project_members",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 38,
                    'accessibilities_name' => "hrms:travel_order",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 39,
                    'accessibilities_name' => "hrms:setup_division",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 40,
                    'accessibilities_name' => "hrms:setup_position",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 41,
                    'accessibilities_name' => "hrms:setup_allowance",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 42,
                    'accessibilities_name' => "hrms:setup_settings",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 43,
                    'accessibilities_name' => "hrms:setup_salary_grade",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 44,
                    'accessibilities_name' => "accounting:chart_of_accounts",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 45,
                    'accessibilities_name' => "accounting:books",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 46,
                    'accessibilities_name' => "accounting:transaction_type",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 47,
                    'accessibilities_name' => "accounting:document_Series",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 48,
                    'accessibilities_name' => "accounting:posting_period",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 49,
                    'accessibilities_name' => "accounting:account_groups",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 50,
                    'accessibilities_name' => "accounting:stake_holder",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 51,
                    'accessibilities_name' => "project_monitoring:dashboard",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 52,
                    'accessibilities_name' => "project_monitoring:projects",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],



                [
                    'id' => 53,
                    'accessibilities_name' => "hrms:dashboard_announcement",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 54,
                    'accessibilities_name' => "hrms:dashboard_birthday",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 55,
                    'accessibilities_name' => "hrms:dashboard_lates",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 56,
                    'accessibilities_name' => "hrms:dashboard_absent",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 57,
                    'accessibilities_name' => "hrms:dashboard_absent_chart",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 58,
                    'accessibilities_name' => "hrms:dashboard_assignment_location_chart",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 59,
                    'accessibilities_name' => "hrms:dashboard_gender_chart",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 60,
                    'accessibilities_name' => "hrms:announcement_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 61,
                    'accessibilities_name' => "hrms:announcement_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 62,
                    'accessibilities_name' => "hrms:attendance_attendance_portal_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 63,
                    'accessibilities_name' => "hrms:attendance_attendance_portal_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 64,
                    'accessibilities_name' => "hrms:attendance_daily_logs_record_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 65,
                    'accessibilities_name' => "hrms:attendance_daily_logs_record_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 66,
                    'accessibilities_name' => "hrms:attendance_daily_logs_record_approval",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 67,
                    'accessibilities_name' => "hrms:event_calendar_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 68,
                    'accessibilities_name' => "hrms:event_calendar_calendar",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 69,
                    'accessibilities_name' => "hrms:employee_201_PIS",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 70,
                    'accessibilities_name' => "hrms:employee_201_staff_information_sheet",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 71,
                    'accessibilities_name' => "hrms:employee_201_documents_memos",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 72,
                    'accessibilities_name' => "hrms:employee_201_id",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 73,
                    'accessibilities_name' => "hrms:employee_personnel_action_notice_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 74,
                    'accessibilities_name' => "hrms:employee_personnel_action_notice_all_request",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 75,
                    'accessibilities_name' => "hrms:employee_personnel_action_notice_approval",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 76,
                    'accessibilities_name' => "hrms:employee_personnel_action_notice_my_request",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 77,
                    'accessibilities_name' => "hrms:_manpower_request_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 78,
                    'accessibilities_name' => "hrms:_manpower_request_all_request",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 79,
                    'accessibilities_name' => "hrms:_manpower_request_approval",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 80,
                    'accessibilities_name' => "hrms:_manpower_request_my_request",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 81,
                    'accessibilities_name' => "hrms:loans_and_advances_cash_advance_forms",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 82,
                    'accessibilities_name' => "hrms:loans_and_advances_cash_advance_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 83,
                    'accessibilities_name' => "hrms:loans_and_advances_cash_advance_approvals",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 84,
                    'accessibilities_name' => "hrms:loans_and_advances_loans_forms",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 85,
                    'accessibilities_name' => "hrms:loans_and_advances_loans_loans_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 86,
                    'accessibilities_name' => "hrms:loans_and_advances_loans_payment_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 87,
                    'accessibilities_name' => "hrms:loans_and_advances_other_deduction_forms",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 88,
                    'accessibilities_name' => "hrms:loans_and_advances_other_deduction_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 89,
                    'accessibilities_name' => "hrms:leave_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 90,
                    'accessibilities_name' => "hrms:leave_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 91,
                    'accessibilities_name' => "hrms:leave_my_approvals",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 92,
                    'accessibilities_name' => "hrms:overtime_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 93,
                    'accessibilities_name' => "hrms:overtime_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 94,
                    'accessibilities_name' => "hrms:overtime_my_request",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 95,
                    'accessibilities_name' => "hrms:overtime_my_approvals",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 96,
                    'accessibilities_name' => "hrms:travel_order_form",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 97,
                    'accessibilities_name' => "hrms:travel_order_list",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 98,
                    'accessibilities_name' => "hrms:travel_order_my_request",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 99,
                    'accessibilities_name' => "hrms:travel_order_my_approvals",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 100,
                    'accessibilities_name' => "hrms:attendance_attendance_logs",
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],

            ],
            [ "id" ],
            [ "accessibilities_name" ]
        );
    }
}
