<?php

namespace Database\Seeders;

use App\Enums\AccessibilityHrms;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AccessibilitiesSeederHrms extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // HRMS
        DB::table('accessibilities')->upsert(
            [
                [
                    'id' => 1,
                    'accessibilities_name' => AccessibilityHrms::HRMS_DASHBOARD->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ANNOUNCEMENT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCEPORTAL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_DTR->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_FAILURETOLOG->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 6,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_FACERECOGNITION->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 7,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCELOGIN->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 8,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_QR->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 9,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EVENTCALENDAR->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 10,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REQUEST_VOID_CREATEREQUEST,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 11,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REQUEST_VOID_ALLREQUEST,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 12,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REQUEST_VOID_MYAPPROVALS,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 13,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCELOGSDELETE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 14,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_USERACCOUNT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 15,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_DEPARTMENT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 17,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_APPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 18,
                    'accessibilities_name' => AccessibilityHrms::HRMS_HMO->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 19,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_PAGIBIG->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 20,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_PHILHEALTH->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 21,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_SSS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 22,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_WITHHOLDINGTAX->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 23,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_LEAVES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 24,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_PAYROLLPARTICULARS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 25,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_13THMONTH_SUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 26,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_LOANS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 27,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_OTHERDEDUCTIONS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 28,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_13THMONTH_FORMANDMYREQUEST->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 29,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_13THMONTH_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 30,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_13THMONTH_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 31,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_ALLOWANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 32,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_PAYROLLRECORD->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 33,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 34,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SCHEDULE_DEPARTMENT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 35,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SCHEDULE_EMPLOYEE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 36,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SCHEDULE_PROJECT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 37,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOCATION_EMPLOYEES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 38,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 39,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 40,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_POSITION->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 41,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_ALLOWANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 42,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_SETTINGS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 43,
                    'accessibilities_name' => AccessibilityHrms::HRMS_SETUP_SALARY_GRADE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 44,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_GENERATEPAYROLL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 45,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_GENERATEPAYROLL_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 46,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_GENERATEPAYROLL_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 47,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARYDISBURSEMENT_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 48,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARYDISBURSEMENT_AllREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 49,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARYDISBURSEMENT_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 50,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARYDISBURSEMENT_VIEWPAYSLIPS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 51,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 52,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 53,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 54,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 55,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 56,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 57,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 58,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 59,
                    'accessibilities_name' => "",
                    'deleted_at' =>  Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 60,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 61,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 62,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 63,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 64,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 65,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 66,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 67,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_EDIT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 68,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 69,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_PIS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 70,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_STAFFINFOSHEET->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 71,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_DOCUMENTSMEMO->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 72,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_201_ID->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 73,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_FORM_NEWHIRE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 74,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 75,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 76,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_FORM_TRANSFER->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 77,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 78,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 79,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 80,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_MYREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 81,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_CASHADVANCE_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 82,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_CASHADVANCE_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 83,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LOANSANDADVANCES_CASHADVANCE_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 84,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_FORM_PROMOTION->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 85,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_FORM_TERMINATION->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 86,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_FORM_MEMO->value,
                    'deleted_at' => Carbon::now(), // TEMPORARY DELETE READY FOR WHEN IMPLEMENTED
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 87,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_PAN_FORM_BULKTRANSFER->value,
                    'deleted_at' => Carbon::now(), // TEMPORARY DELETE READY FOR WHEN IMPLEMENTED
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 88,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 89,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_LEAVE_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 90,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_LEAVE_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 91,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_LEAVE_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 92,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_OVERTIME_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 93,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_OVERTIME_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 94,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_OVERTIME_MYREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 95,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_OVERTIME_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 96,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_TRAVELORDER_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 97,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_TRAVELORDER_ALLREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 98,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_TRAVELORDER_MYREQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 99,
                    'accessibilities_name' => AccessibilityHrms::HRMS_LNOTNTO_TRAVELORDER_MYAPPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 100,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCELOGS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 101,
                    'accessibilities_name' => AccessibilityHrms::HRMS_ATTENDANCE_ATTENDANCE_QR->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 102,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 110,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_SSSEMPLOYEEREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 120,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PAGIBIGEMPLOYEEREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 130,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PHILHEALTHEMPLOYEEREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 140,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_SSSGROUPREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 150,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PAGIBIGGROUPREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 160,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PHILHEALTHGROUPREMITTANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 170,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_SSSREMITTANCESUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 180,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PAGIBIGREMITTANCESUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 190,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PHILHEALTHREMITTANCESUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 200,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_LOAN->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 201,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_ADMINISTRATIVE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 210,
                    'accessibilities_name' => AccessibilityHrms::HRMS_PAYROLL_SALARY_GENERATE_PAYROLL_CHANGE_OF_CHARGING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 220,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_FORM_REQUESTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 230,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_OPEN_POSITIONS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 240,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_APPLICATION_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 250,
                    'accessibilities_name' => AccessibilityHrms::HRMS_EMPLOYEE_MANPOWERREQUEST_APPLICANTS_JOB->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 260,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_OVERTIMEMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 270,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_SALARYMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 280,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_OVERTIMEMONITORINGSUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 290,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_FAILURETOLOGMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 300,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_FAILURETOLOGMONITORINGSUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 310,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_LEAVEMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 320,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_LEAVEMONITORINGSUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 330,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_TRAVELORDERMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 340,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_TRAVELORDERMONITORINGSUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 350,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_MANPOWERREQUESTMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 360,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_PANTRANSFERMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 370,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_PANTERMINATIONMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 380,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_PANPROMOTIONMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 390,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_MANPOWERREQUESTMONITORINGSUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 400,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_ATTENDANCELOGMONITORING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 410,
                    'accessibilities_name' => AccessibilityHrms::HRMS_REPORTS_PORTALMONITORING_ATTENDANCELOGMONITORINGSUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ],
            [ "id" ],
            [ "accessibilities_name", "deleted_at"]
        );
    }
}
