<?php

namespace Database\Seeders;

use App\Enums\AccessibilityAccounting;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AccessibilitiesSeederAccounting extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ACCOUNTING
        DB::table('accessibilities')->upsert(
            [
                [
                    'id' => 1001,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1002,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1003,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1004,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1005,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1006,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1007,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1008,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1020,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1030,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1040,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1040,
                    'accessibilities_name' => "",
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1050,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_DASHBOARD->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1060,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_APPROVALS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1070,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_ACCOUNTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1080,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_BOOK_OF_ACCOUNTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1090,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_ACCOUNT_GROUPS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1100,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_ACCOUNT_TYPES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1110,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_POSTING_PERIODS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1120,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_CHART_OF_ACCOUNTS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1130,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_STAKEHOLDERS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1140,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_SYNCHRONIZATION->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1150,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REQUEST_PURCHASE_ORDER->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1160,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REQUEST_NON_PURCHASE_ORDER->value,
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1163,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REQUEST_NON_PURCHASE_ORDER_ALL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1166,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REQUEST_NON_PURCHASE_ORDER_MY_APPROVAL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1169,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REQUEST_NON_PURCHASE_ORDER_MY_REQUEST->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1170,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REQUEST_PRE_PAYROLL_AUDIT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1180,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_DISBURSEMENT->value,
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1183,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_DISBURSEMENT_ALL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1186,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_DISBURSEMENT_MY_REQUEST->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1188,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_DISBURSEMENT_MY_APPROVAL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1189,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_DISBURSEMENT_FOR_DISBURSEMENT_VOUCHER->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1190,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_CASH->value,
                    'deleted_at' => Carbon::now(),
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1192,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_CASH_ALL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1194,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_CASH_MY_REQUEST->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1196,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_CASH_MY_APPROVAL->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1197,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_CASH_FOR_CASH_VOUCHER->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1198,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_CASH_CLEARED->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1199,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_VOUCHER_CASH_FOR_CLEARING->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1200,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_JOURNAL_ENTRY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1203,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_JOURNAL_ENTRY_CASH_ENTRIES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1206,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_JOURNAL_ENTRY_DISBURSEMENT_ENTRIES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1209,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_JOURNAL_ENTRY_FOR_PAYMENT_ENTRIES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1210,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_PARTICULAR_GROUP->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1220,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_TERMS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1231,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_BALANCE_SHEET->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1232,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_BOOK_BALANCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1233,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_EXPENSES_FOR_THE_MONTH->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1234,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_INCOME_STATEMENT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1235,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_MONTHLY_PROJECT_EXPENSES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1236,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_MONTHLY_UNLIQUIDATED_CASH_ADVANCES->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1237,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_STATEMENT_OF_CASH_FLOW->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1238,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_OFFICE_CODE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1239,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_OFFICE_HUMAN_RESOURCE->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1240,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_SETUP_WITHHOLDING_TAX->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1251,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_LIQUIDATION_FORM->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1252,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_REPLENISHMENT_SUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1253,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_CASH_ADVANCE_SUMMARY->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1254,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_MEMORANDUM_OF_DEPOSIT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1255,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_PROVISIONAL_RECEIPT->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1256,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_CASH_RETURN_SLIP->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id' => 1257,
                    'accessibilities_name' => AccessibilityAccounting::ACCOUNTING_REPORTS_PAYROLL_LIQUIDATIONS->value,
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ],
            [ "id" ],
            [ "accessibilities_name", "deleted_at"]
        );
    }
}
