<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreJobApplicantsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'manpowerrequests_id'=> [
                "required",
                "integer",
                "exists:manpower_requests,id",
            ],
            'application_name'=>[
                "required",
                "string",
            ],
            'application_letter_attachment'=>[
                "required",
                "max:10000",
                "mimes:application/msword,doc,docx,pdf,zip",
            ],
            'resume_attachment'=>[
                "required",
                "max:10000",
                "mimes:application/msword,doc,docx,pdf,zip",
            ],
            'status'=>[
                "required",
                "string",
                'in:Pending,Interviewed,Rejected,Hired'
            ],
            'lastname'=>[
                "required",
                "string",
                "max:35"
            ],
            'firstname'=>[
                "required",
                "string",
                "max:35"
            ],
            'middlename'=>[
                "required",
                "string",
                "max:35"
            ],
            'date_of_application'=>[
                "required",
                "date",
            ],
            'date_of_birth'=>[
                "required",
                "date",
            ],
            'address_street'=>[
                "required",
                "string",
            ],
            'address_city'=>[
                "required",
                "string",
            ],
            'address_zip'=>[
                "required",
                "string",
            ],
            'contact_info'=>[
                "required",
                "string",
                "min:11",
                "max:11",
            ],
            'email'=>[
                "required",
                "string",
                "max:35"
            ],
            'how_did_u_learn_about_our_company'=>[
                "required",
                "string",
            ],
            'desired_position'=>[
                "required",
                "string",
            ],
            'currently_employed'=>[
                "required",
                "string",
                'in:Yes,No'
            ],
            'name_of_spouse'=>[
                "nullable",
                "string",
                "max:55"
            ],
            'date_of_birth_spouse'=>[
                "nullable",
                "date",
            ],
            'occupation_spouse'=>[
                "nullable",
                "string",
            ],
            'telephone_spouse'=>[
                "nullable",
                "string",
                "min:11",
                "max:11",
            ],
            'children'=>[
                "nullable",
                "json",
            ],
            'children.*.name'=>[
                "required_with:children.*.birthdate",
                "string",
            ],
            'children.*.birthdate'=>[
                "required_with:children.*.name",
                "date",
            ],
            'icoe_name'=>[
                "required",
                "string",
            ],
            'icoe_address'=>[
                "required",
                "string",
            ],
            'icoe_relationship'=>[
                "required",
                "string",
            ],
            'telephone_icoe'=>[
                "required",
                "string",
                "min:11",
                "max:11",
            ],
            'education'=>[
                "required",
                "json",
            ],
            'education.*.elementary_name'=>[
                "required",
                "string",
            ],
            'education.*.elementary_education'=>[
                "required",
                "string",
            ],
            'education.*.elementary_period_attendance_to'=>[
                "required",
                "date",
            ],
            'education.*.elementary_period_attendance_from'=>[
                "required",
                "date",
            ],
            'education.*.elementary_year_graduated'=>[
                "required",
                "date",
            ],
            'education.*.secondary_name'=>[
                "required",
                "string",
            ],
            'education.*.secondary_education'=>[
                "required",
                "string",
            ],
            'education.*.secondary_period_attendance_to'=>[
                "required",
                "date",
            ],
            'education.*.secondary_period_attendance_from'=>[
                "required",
                "date",
            ],
            'education.*.secondary_year_graduated'=>[
                "required",
                "date",
            ],
            'education.*.vocationalcourse_name'=>[
                "required",
                "string",
            ],
            'education.*.vocationalcourse_education'=>[
                "required",
                "string",
            ],
            'education.*.vocationalcourse_period_attendance_to'=>[
                "required",
                "date",
            ],
            'education.*.vocationalcourse_period_attendance_from'=>[
                "required",
                "date",
            ],
            'education.*.vocationalcourse_year_graduated'=>[
                "required",
                "date",
            ],
            'education.*.college_name'=>[
                "required",
                "string",
            ],
            'education.*.college_education'=>[
                "required",
                "string",
            ],
            'education.*.college_period_attendance_to'=>[
                "required",
                "date",
            ],
            'education.*.college_period_attendance_from'=>[
                "required",
                "date",
            ],
            'education.*.college_year_graduated'=>[
                "required",
                "date",
            ],
            'education.*.graduatestudies_name'=>[
                "required",
                "string",
            ],
            'education.*.graduatestudies_education'=>[
                "required",
                "string",
            ],
            'education.*.graduatestudies_period_attendance_to'=>[
                "required",
                "date",
            ],
            'education.*.graduatestudies_period_attendance_from'=>[
                "required",
                "date",
            ],
            'education.*.graduatestudies_year_graduated'=>[
                "required",
                "date",
            ],
            'workexperience'=>[
                "nullable",
                "json",
            ],
            'workexperience.*.inclusive_dates_from'=>[
                "nullable",
                "date",
            ],
            'workexperience.*.inclusive_dates_to'=>[
                "nullable",
                "date",
            ],
            'workexperience.*.position_title'=>[
                "nullable",
                "string",
            ],
            'workexperience.*.dpt_agency_office_company'=>[
                "nullable",
                "string",
            ],
            'workexperience.*.monthly_salary'=>[
                "nullable",
                "float",
            ],
            'workexperience.*.status_of_appointment'=>[
                "nullable",
                "string",
            ],
        ];
    }
}
