<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UpdateEmployeeEducationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            'employee_id'=> [
                "nullable",
                "integer",
                "exists:employees,id",
            ],
            'elementary_name'=>[
                "nullable",
                "string",
            ],
            'elementary_education'=>[
                "nullable",
                "string",
            ],
            'elementary_period_attendance_to'=>[
                "nullable",
                "string",
            ],
            'elementary_period_attendance_from'=>[
                "nullable",
                "string",
            ],
            'elementary_year_graduated'=>[
                "nullable",
                "string",
            ],
            'secondary_name'=>[
                "nullable",
                "string",
            ],
            'secondary_education'=>[
                "nullable",
                "string",
            ],
            'secondary_period_attendance_to'=>[
                "nullable",
                "string",
            ],
            'secondary_period_attendance_from'=>[
                "nullable",
                "string",
            ],
            'secondary_year_graduated'=>[
                "nullable",
                "string",
            ],
            'vocationalcourse_name'=>[
                "nullable",
                "string",
            ],
            'vocationalcourse_education'=>[
                "nullable",
                "string",
            ],
            'vocationalcourse_period_attendance_to'=>[
                "nullable",
                "string",
            ],
            'vocationalcourse_period_attendance_from'=>[
                "nullable",
                "string",
            ],
            'vocationalcourse_year_graduated'=>[
                "nullable",
                "string",
            ],
            'college_name'=>[
                "nullable",
                "string",
            ],
            'college_education'=>[
                "nullable",
                "string",
            ],
            'college_period_attendance_to'=>[
                "nullable",
                "string",
            ],
            'college_period_attendance_from'=>[
                "nullable",
                "string",
            ],
            'college_year_graduated'=>[
                "nullable",
                "string",
            ],
            'graduatestudies_name'=>[
                "nullable",
                "string",
            ],
            'graduatestudies_education'=>[
                "nullable",
                "string",
            ],
            'graduatestudies_period_attendance_to'=>[
                "nullable",
                "string",
            ],
            'graduatestudies_period_attendance_from'=>[
                "nullable",
                "string",
            ],
            'graduatestudies_year_graduated'=>[
                "nullable",
                "string",
            ],
            'elementary_degree_earned_of_school'=>[
                "nullable",
                "string",
            ],
            'elementary_honors_received'=>[
                "nullable",
                "string",
            ],
            'secondary_degree_earned_of_school'=>[
                "nullable",
                "string",
            ],
            'secondary_honors_received'=>[
                "nullable",
                "string",
            ],
            'college_degree_earned_of_school'=>[
                "nullable",
                "string",
            ],
            'college_honors_received'=>[
                "nullable",
                "string",
            ],
            'vocationalcourse_degree_earned_of_school'=>[
                "nullable",
                "string",
            ],
            'vocationalcourse_honors_received'=>[
                "nullable",
                "string",
            ],
        ];
    }
}
