<?php

namespace App\Enums\Reports;

enum AdministrativeReport: string
{
    case EMPLOYEE_MASTERLIST = "EMPLOYEE MASTERLIST";
    case EMPLOYEE_NEWHIRE = "EMPLOYEE NEWHIRE";
    case EMPLOYEE_TENURESHIP = "EMPLOYEE TENURESHIP";
    case EMPLOYEE_LEAVES = "EMPLOYEE LEAVES";
    case EMPLOYEE_ABSENTIES = "EMPLOYEE ABSENTIES";
}
