<?php

namespace App\Enums\Reports;

enum PortalMonitoringReport: string
{
    case OVERTIME_MONITORING = "OVERTIME MONITORING";
    case SALARY_MONITORING = "SALARY MONITORING";
    case OVERTIME_MONITORING_SUMMARY = "OVERTIME MONITORING SUMMARY";
    case FAILURE_TO_LOG_MONITORING = "FAILURE TO LOG MONITORING";
    case FAILURE_TO_LOG_MONITORING_SUMMARY = "FAILURE TO LOG MONITORING SUMMARY";
    case LEAVE_MONITORING = "LEAVE MONITORING";
    case LEAVE_MONITORING_SUMMARY = "LEAVE MONITORING SUMMARY";
    case TRAVEL_ORDER_MONITORING = "TRAVEL ORDER MONITORING";
    case TRAVEL_ORDER_MONITORING_SUMMARY = "TRAVEL ORDER MONITORING SUMMARY";
    case MANPOWER_REQUEST_MONITORING = "MANPOWER REQUEST MONITORING";
    case PAN_TERMINATION_MONITORING = "PAN TERMINATION MONITORING";
    case PAN_TRANSFER_MONITORING = "PAN TRANSFER MONITORING";
    case PAN_PROMOTION_MONITORING = "PAN PROMOTION MONITORING";
}
